name: build

on:
  pull_request:
    branches: [main, master, alpha, beta]
  workflow_call:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: Fail the build v2
        run: exit 1
